name: Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: Create a new CTP release if set to true
        required: false
        default: 'false'
      target_branch:
        description: Target Branch
        required: true
        default: main
      release_notes:
        description: Release Notes
        required: false
  push:
    branches:
      - main
    paths:
      - 'docs/ctp/**'
      - 'testplans/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/ctp/**'
      - 'testplans/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y make ruby

      - name: Install gems
        run: sudo gem install asciidoctor asciidoctor-pdf

      - name: Build
        run: make -j2

      - name: Make GitHub pages directory
        run: |
          mkdir github-pages
          cp docs/ctp/ctp.html github-pages/index.html

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: ctp.pdf
          path: docs/ctp/ctp.pdf

      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: ctp.html
          path: docs/ctp/ctp.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages

  draft-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: ctp.pdf
          path: ./

      - name: Download HTML
        uses: actions/download-artifact@v4
        with:
          name: ctp.html
          path: ./

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d')"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: draft-${{ steps.date.outputs.date }}-${{ github.sha }}
          release_name: Draft release ${{ steps.date.outputs.date }}
          body: Latest snapshot (${{ github.sha }})
          prerelease: true

      - name: Upload PDF
        id: upload-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ctp.pdf
          asset_name: ctp.pdf
          asset_content_type: application/pdf


      - name: Upload HTML
        id: upload-html
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ctp.html
          asset_name: ctp.html
          asset_content_type: text/html

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: ctp.pdf
          path: ./

      - name: Download HTML
        uses: actions/download-artifact@v4
        with:
          name: ctp.html
          path: ./

      - name: Upload PDF
        id: upload-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ctp.pdf
          asset_name: ctp.pdf
          asset_content_type: application/pdf

      - name: Upload HTML
        id: upload-html
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ctp.html
          asset_name: ctp.html
          asset_content_type: text/html

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
