---
name: CTP Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: Create a new CTP release if set to true
        required: false
        default: 'false'
      target_branch:
        description: Target Branch
        required: true
        default: main
      release_notes:
        description: Release Notes
        required: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

    # Set the short SHA for use in artifact names
      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

    # Get the current date
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    # Build PDF and HTML files using the container
      - name: Build Files
        id: build_files
        run: make -C docs/ctp -j$(nproc)

    # Upload the CTP PDF file
      - name: Upload ctp.pdf
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ctp-${{ env.SHORT_SHA }}.pdf
          path: ${{ github.workspace }}/docs/ctp/ctp.pdf
          retention-days: 7

    # Upload the CTP HTML file
      - name: Upload ctp.html
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ctp-${{ env.SHORT_SHA }}.html
          path: ${{ github.workspace }}/docs/ctp/ctp.html
          retention-days: 7

      - name: Create Release
        if: steps.build_files.outcome == 'success' && github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true'
        #uses: softprops/action-gh-release@v2.2.2
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          draft: false
          tag_name: ctp-release-${{ env.SHORT_SHA }}-${{ env.CURRENT_DATE }}
          name: ${{ env.CURRENT_DATE }}
          body: |
            This release was created by: ${{ github.event.sender.login }}
            Release Notes: ${{ github.event.inputs.release_notes }}
          files: |
            ${{ github.workspace }}/docs/ctp/ctp.pdf
            ${{ github.workspace }}/docs/ctp/ctp.html

    # Create directory structure pages sites for privileged and unprivileged specs.
      - name: Make GitHub pages directory
        run: |
          mkdir -p dist/snapshot/ctp
          cp docs/ctp/ctp.html dist/snapshot/ctp/index.html
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

  # Deploy HTML to GitHub pages.
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
